### PR TITLE
Add shorty to the short list

### PR DESCRIPTION
**Pull request by s-k-z**
I don't know if attacking familiar has any negative consequences here.

### CODE REVIEW

**Comment by horrible-little-slime** [comment]
I'm not sure if this is meaningfully stronger than snapper; would it be worth giving this an additional bonus value in free fight familiar valuation instead?

**Comment by s-k-z** [comment]
Hmm, that's a good point, but I don't know what it is worth either. 1 rose? 2 roses?

**Comment by horrible-little-slime** [comment]
I think any familiar that attacks is worth 1 rose, which is kind of fun code to add

**Comment by s-k-z** [comment]
Gonna close this since it's kind of an incomplete idea for now.

**Pull request closed without merging**
